# Generated by Django 3.2.9 on 2021-11-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coat',
            old_name='size',
            new_name='sex',
        ),
    ]
