# Generated by Django 3.2.9 on 2021-11-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_size_coat_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='coat',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coat',
            name='size',
            field=models.CharField(choices=[('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('Xl', 'Xl'), ('XXl', 'Xxl')], max_length=5, null=True),
        ),
    ]
