# Generated by Django 3.2.9 on 2021-11-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211130_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coat',
            name='size',
        ),
    ]
