# Generated by Django 3.2.9 on 2021-11-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_coatsize_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='coat',
            name='available_size',
            field=models.ManyToManyField(to='shop.CoatSize'),
        ),
    ]
