# Generated by Django 3.2.9 on 2021-11-30 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20211130_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 30, 19, 29, 47, 673716, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
