# Generated by Django 3.2.9 on 2021-11-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='created_at',
        ),
    ]
