# Generated by Django 3.2.9 on 2021-12-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20211130_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coat',
            name='sex',
            field=models.CharField(choices=[('Муж', 'Male'), ('Жен', 'Female')], max_length=3),
        ),
        migrations.AlterField(
            model_name='coat',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
